FROM ruby:3.3.6-slim

RUN apt-get update -qq && \
    apt-get install --no-install-recommends -y \
      build-essential curl git libpq-dev libyaml-dev pkg-config postgresql-client && \
    rm -rf /var/lib/apt/lists /var/cache/apt/archives

WORKDIR /app

COPY Gemfile Gemfile.lock ./
RUN gem install bundler -v 2.5.0 --no-document && \
    bundle _2.5.0_ install

COPY . .

EXPOSE 8000

ENTRYPOINT ["./bin/docker-entrypoint-dev"]
CMD ["bundle", "exec", "rails", "server", "-p", "8000", "-b", "0.0.0.0"]
